### ISSUE TITLE
charm-repo mount fails if it is a symlink farm

### ISSUE THREAD

**Issue by stub42** [whitmo/jujubox#13]
It is common for $JUJU_REPOSITORY to be a directory structure full of symlinks pointing to actual charms. When it is mounted as charm-repo, these symlinks no longer point to anything valid.

Is the charm-repo needed at all? The repository structure could be build easily enough given a number of charm directories, perhaps making it easier to test a charm against multiple series.

**Comment by stub42** [comment]
There are similar fails if the branch is a light checkout, and the actual repository elsewhere (which is possibly a bundletester issue, as it really has no business poking at my VCS setup).

**Comment by lazypower** [comment]
@stub42  i'm not really sure what you're doing here... 

From what I gather, you're symlinking charms in your $JUJU_REPOSITORY, and this is failing in the docker box as it cannot resolve the linked path?

**Comment by stub42** [comment]
Yes. I think this issue is bogus, as I can't see anything sane for jujubox to do.

**Comment by lazypower** [comment]
@stub42 Even though this issue is closed - I've written a quick post about context switching that may help you and your workflow here:

http://blog.dasroot.net/2015-local-isolation-with-docker-and-juju.html

While i'm not doing symlinks of charms - i'm managing contexts of the charms in which I am working on, and have isolated silos of charms. This may be along the lines of what you're looking to achieve here.
